config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root 'home#index'
  
  get 'home/index'
  get '/home/new'
  get '/home/posts'
  post '/home/create'
  get '/home/edit/:id' => 'home#edit'
  post '/home/update/:id' => 'home#update'
  get 'home/destroy/:id' => 'home#destroy'
  post '/home/comment_create/:id' => 'home#comment_create'
  get 'likes/toggle/:id' => "likes#toggle"
  get '/home/posts/:id' => "home#posts"
  get '/home/all_post'
  get '/home/search'
  get '/home/profile/:id' => 'home#profile'
  get '/home/profile_posts/:id' => "home#profile_posts"
  get '/follow/create/:id' => "follow#create"
  get '/follow/destroy/:id' => "follow#destroy"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :user
belongs_to :post
    
end

app/models/follow.rb
class Follow < ActiveRecord::Base
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User" 
    

end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to:post
    belongs_to:user
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to:user
    has_many:comments
    has_many:likes
    has_many:liked_users, through: :likes, source: :user
    mount_uploader:image, PostImageUploader
    
   
    def self.search(search)
       
       search = Post.where("title LIKE ? or content LIKE ?" , "%#{search}%","%#{search}%")
        
    end
    


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many:posts
         has_many:comments
         
         has_many:likes
         has_many:liked_posts, through: :likes, source: :post
   
         has_many:follower_relations, foreign_key: "followed_id", class_name:"Follow"
         has_many:followers, through: :follower_relations, source: :follower
         has_many:following_relations, foreign_key: "follower_id", class_name:"Follow"
         has_many:followings, through: :following_relations, source: :followed
         mount_uploader:avatar, AvatarUploader
         
         

         
         
         
         
         def is_like?(p)
             
         like=Like.find_by(user_id:self.id, post_id:p.id).present?
         
         end
         
         
         
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    devise_parameter_sanitizer.permit(:update_account, keys: [:avatar])
  end
end

app/controllers/follow_controller.rb
class FollowController < ApplicationController
    
    def create
    
    follow=Follow.new
    follow.followed_id=params[:id]
    follow.follower_id=current_user.id
    follow.save
    redirect_to :back
    end
    
    def destroy
    follow=Follow.find_by(followed_id:params[:id], follower_id: current_user.id)
    follow.destroy
    
    redirect_to :back
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 before_action:authenticate_user!
 before_action:check_ownership, only:[:edit, :update, :destroy]
 require 'will_paginate/array'
  def index
    @posts=Post.all.reverse.paginate(page: params[:page], per_page: 3)
    
  end
  
  def new
    
  end
  
  def posts
      @posts = Post.find_by(id: params[:id])
        
    
  end
  
  def all_post
    @posts=Post.all.reverse
  end
  
  def create
    post = Post.create(title:params[:title], content:params[:content], user_id:current_user.id, image:params[:image])
    post.save
    
    redirect_to '/home/index'
    
  end
  
  def edit
    @post = Post.find_by(id:params[:id])
    
    
  end
  
  def update
    post = Post.find_by(id:params[:id])
    post.title=params[:title]
    post.content=params[:content]
    if post.save
    
    redirect_to '/home/posts'
    
    else redirect_to :back
    
   end
  end
  
  def destroy
    post = Post.find_by(id:params[:id])
    post.destroy
    
    redirect_to :back
    

  end
  
  def comment_create
    
  comment = Comment.new
  comment.user_id = current_user.id
  comment.post_id = params[:id]
  comment.content = params[:content]
  comment.save

  redirect_to :back
  end
  
    
  def search
    @search = Post.search(params[:search])
    if !@search.present?
      flash[:alert]="no result"
    end
  end
  
  
  def profile
    @posts=Post.find_by(id:params[:id])
    
  end
  
  def profile_posts
    @profile_user = User.find_by(id:params[:id])
  end
  
  private
  
  def check_ownership
    post = Post.find_by(id:params[:id])
    redirect_to '/home/index' if current_user.id != post.user_id
    
  end

  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def toggle
    like=Like.find_by(user_id:current_user, post_id:params[:id])
    if like.nil?
      like=Like.new
      like.post_id=params[:id]
      like.user_id=current_user.id
      like.save
      
      render integer: like.post_id, integer: like.user_id
         
   
    else
       like=Like.find_by(user_id:current_user, post_id:params[:id])
       like.destroy
       like.save
       
       redirect_to :back
       
     end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/home/all_post.html.erb
    <section id="new">
        <div class="container">
            
          <% @posts.each do |p| %>
            <form>
                <input class="title_input form-control" type="text" placeholder="Enter the title..." name="title" value="<%=p.title%>">
                <div class="content_box">
                    <textarea class="form-control" type="text" cols="150" rows="15" name="content"><%=p.content%></textarea>
                <div class="like_wrapper">
                    <p>좋아하는 사람들 수 : <%=p.likes.count%></p>
                    <% if current_user.is_like?(p) %>
                        <a href="/likes/toggle/<%=p.id%>">좋아요 취소</a>
                    <% else %>
                        <a href="/likes/toggle/<%=p.id%>">좋아요</a>
                    <% end %>
                </div>    
                    
                </div>
                    <% if current_user.id == p.user.id %>    
                        <button class="button_3 right" ><a href="/home/edit/<%=p.id%>">Edit</a></button>
                        <button class="button_4 right"><a href="/home/destroy/<%=p.id%>">Destroy</a></button>
                    <% end %>
                    
                  <textarea class="form-control" cols="150" rows="3">
                    <% p.comments.each do |c|%>
                   <%=c.user.email%>님의 댓글 : <%=c.content%>
                    <% end %> 
                  </textarea>
             </div>
            </form>    
            
             
                    <div class="input-field col s12">
                        <form action="/home/comment_create/<%=p.id%>" method="POST">
                            <textarea id="textarea2" class="materialize-textarea" data-length="120" name="content"></textarea>
                            <input type="submit" value="댓글작성">
                        </form>
                    </div>
               <% end %>
        </div>
    </section>

app/views/home/edit.html.erb
<h1>수정하기</h1> 
   
   <section id="new">
        <div class="container">
            <form action="/home/update/<%=@post.id%>" method="POST">
                <input value="<%=@post.title%>" class="title_input form-control" type="text" placeholder="Enter the title..." name="title">
                <div class="content_box">
                    <textarea class="form-control" type="text" cols="150" rows="15" name="content"><%=@post.content%></textarea>
                </div>
                <button type="submit" class="button_2">Update</button>
            </form>
        </div>
    </section>

app/views/home/index.html.erb
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="home.scss">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <title>Acme Web Design | Welcome</title>
</head>
<body>

  
    <section id="showcase">
        <div class="container">
            <h1>Trip To Thailand, Backpacker!</h1>
            <p>Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur,<br> from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.</p>
            <form action="/home/search" method="get">
                <input type="text" placeholder="Search..." name="search">
                <button class="button_1" type="submit">Search</button>
            </form>
        </div>
    </section>
    <section id="boxes">
        <div class="container">
            <% @posts.each do |p| %>
            <div class="box">
                <% if p.image.url %>
                <img src="<%=p.image.url%>">
                <% end %>
                <h2><a href="/home/posts/<%=p.id%>"><%=p.title%></a></h2>
                        <hr>
                <h5><%= truncate p.content, length: 30 %><%=link_to 'read more', home_create_path(p.id) %></h5>
            </div>
            <% end %>
            
            <%= will_paginate @posts, renderer: BootstrapPagination::Rails, previous_label: "Older", next_label: "Newer", inner_window:1, outer_window:2 %>
        </div>
    </section>

    
    
</body>

app/views/home/new.html.erb
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="home.scss">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <title>Acme Web Design | Welcome</title>
<script>
$(document).ready(function(){
  $(".button_2").click(function(){
    alert("글이 작성되었습니다.");
  });
});
</script>
</script>
</head>

<body>
    <section id="new">
        <div class="container">
            <%=form_tag home_create_path, method:"POST", multipart:"true" do %>
                
                <input class="title_input form-control" type="text" placeholder="Enter the title..." name="title">
                <div class="content_box">
                    <textarea class="form-control" type="text" cols="150" rows="15" name="content"></textarea>
                </div>
                <%=file_field_tag :image %><br>
                <button type="submit" class="button_2">Create</button>
            <%end%>
        </div>
    </section>
    
    
    <div id="wait" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='demo_wait.gif' width="64" height="64" /><br>Loading..</div>
    
</body>

app/views/home/posts.html.erb
<script>
    $.(document).ready(function){
        $.(".like").click(function){
            $.get("likes/toggle/<%=@posts.id%>",
                  function(data){
                  alert("좋아요 완료!")    
                 })
        });
    });
    
</script>

    <section id="new">
        <div class="container">
            <form>
                <div class="thumbwrapper">
                    <% if @posts.user.avatar.url %>
                        <img src="<%=@posts.user.avatar.thumb.url%>" class="thumb_avatar">
                        <a class="thumb" href="/home/profile/<%=@posts.id%>"><%=@posts.user.email%></a>
                    <% end %>    
                </div>
                    <input class="title_input form-control" type="text" placeholder="Enter the title..." name="title" value="<%=@posts.title%>">
                    <div class="content_box">
                        <textarea class="form-control" type="text" cols="150" rows="15" name="content"><%=@posts.content%></textarea>
                    <div class="like_wrapper">
                        <p>좋아하는 사람들 수 : <%=@posts.likes.count%></p>
                        <% if current_user.is_like?(@posts) %>
                            <a class="like">좋아요 취소</a>
                        <% else %>
                            <a class="like">좋아요</a>
                        <% end %>
                    </div>    
                        
                    </div>
                        <% if current_user.id == @posts.user.id %>    
                            <button class="button_3 right" ><a href="/home/edit/<%=@posts.id%>">Edit</a></button>
                            <button class="button_4 right"><a href="/home/destroy/<%=@posts.id%>">Destroy</a></button>
                        <% end %>
                        
                      <textarea class="form-control" cols="150" rows="3">
                        <% @posts.comments.each do |c|%>
                       <%=c.user.email%>님의 댓글 : <%=c.content%>
                        <% end %> 
                      </textarea>
                </div>
             </form>    
            
             
                    <div class="input-field col s12">
                        <form action="/home/comment_create/<%=@posts.id%>" method="POST">
                            <textarea id="textarea2" class="materialize-textarea" data-length="120" name="content"></textarea>
                            <input type="submit" value="댓글작성">
                        </form>
                    </div>
               
        </div>
    </section>

app/views/home/profile.html.erb
<section id="profile">
    <div class="container">
        <div class="card mycustomized_card" style="width: 18rem;">
            <% if @posts.user.avatar.url%>
                <div class="avatar_wrapper">
                   <img src="<%=@posts.user.avatar.url%>" alt="dog">
                </div>   
           <% end %>
          <div class="card-body">
            <h5 class="card-title"><%=@posts.user.email%></h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">게시물 갯수 : <%=@posts.user.posts.count%></li>
            <% if current_user.followings.include?(@posts.user)%>
            <li class="list-group-item"><a href="/home/profile_posts/<%=@posts.user.id%>">쓴 글 보러가기</a></li>
            <% end %>
            <li class="list-group-item">
                팔로잉 : <%=@posts.user.followings.count%>
                팔로우 : <%=@posts.user.followers.count%>
                </li>
          </ul>
          <% if current_user.id != @posts.user.id %>
              <div class="card-body">
                   <% if current_user.followings.include?(@posts.user) %>
                       <a class="card-link" href="/follow/destroy/<%=@posts.user.id%>">팔로우 취소</a>
                   <% else %>
                       <a class="card-link" href="/follow/create/<%=@posts.user.id%>">팔로우</a>
                   <% end %>
              </div>       
          <% end %>
    </div>
</section>

app/views/home/profile_posts.html.erb
 <section id="new">
        <div class="container">
            
          <% @profile_user.posts.each do |p| %>
            <form>
                <input class="title_input form-control" type="text" placeholder="Enter the title..." name="title" value="<%=p.title%>">
                <div class="content_box">
                    <textarea class="form-control" type="text" cols="150" rows="15" name="content"><%=p.content%></textarea>
                <div class="like_wrapper">
                    <p>좋아하는 사람들 수 : <%=p.likes.count%></p>
                    <% if current_user.is_like?(p) %>
                        <a href="/likes/toggle/<%=p.id%>">좋아요 취소</a>
                    <% else %>
                        <a href="/likes/toggle/<%=p.id%>">좋아요</a>
                    <% end %>
                </div>    
                    
                </div>
                    <% if current_user.id == p.user.id %>    
                        <button class="button_3 right" ><a href="/home/edit/<%=p.id%>">Edit</a></button>
                        <button class="button_4 right"><a href="/home/destroy/<%=p.id%>">Destroy</a></button>
                    <% end %>
                    
                  <textarea class="form-control" cols="150" rows="3">
                    <% p.comments.each do |c|%>
                   <%=c.user.email%>님의 댓글 : <%=c.content%>
                    <% end %> 
                  </textarea>
             </div>
            </form>    
            
             
                    <div class="input-field col s12">
                        <form action="/home/comment_create/<%=p.id%>" method="POST">
                            <textarea id="textarea2" class="materialize-textarea" data-length="120" name="content"></textarea>
                            <input type="submit" value="댓글작성">
                        </form>
                    </div>
               <% end %>
        </div>
    </section>

app/views/home/search.html.erb
<section id="new">
        <div class="container">
          <%=flash[:alert]%>
          <% @search.each do |p| %>
            <form>
                <input class="title_input form-control" type="text" placeholder="Enter the title..." name="title" value="<%=p.title%>">
                <div class="content_box">
                    <textarea class="form-control" type="text" cols="150" rows="15" name="content"><%=p.content%></textarea>
                <div class="like_wrapper">
                    <p>좋아하는 사람들 수 : <%=p.likes.count%></p>
                    <% if current_user.is_like?(p) %>
                        <a href="/likes/toggle/<%=p.id%>">좋아요 취소</a>
                    <% else %>
                        <a href="/likes/toggle/<%=p.id%>">좋아요</a>
                    <% end %>
                </div>    
                    
                </div>
                    <% if current_user.id == p.user.id %>    
                        <button class="button_3 right" ><a href="/home/edit/<%=p.id%>">Edit</a></button>
                        <button class="button_4 right"><a href="/home/destroy/<%=p.id%>">Destroy</a></button>
                    <% end %>
                    
                  <textarea class="form-control" cols="150" rows="3">
                    <% p.comments.each do |c|%>
                   <%=c.user.email%>님의 댓글 : <%=c.content%>
                    <% end %> 
                  </textarea>
             </div>
            </form>    
            
             
                    <div class="input-field col s12">
                        <form action="/home/comment_create/<%=p.id%>" method="POST">
                            <textarea id="textarea2" class="materialize-textarea" data-length="120" name="content"></textarea>
                            <input type="submit" value="댓글작성">
                        </form>
                    </div>
               <% end %>
        </div>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
</head>
<body>


     <header>
        <div class="container">
            <div id="branding">
                <p><a href="/home/index">Trippler</a></p>
            </div>
            <div class="nav">
                <ul>
                    <% if user_signed_in? %>
                      <li><a href="/home/index"><span>Home</span></a></li>
                      <li><a href=""><%=current_user.email%></a></li>
                      <li><a href="/home/new">Get Started</a></li>
                      <li><a href="/home/all_post">posts</a></li>
                      <li><%=link_to 'Sign Out', destroy_user_session_path, method:"DELETE"%></li>
                    <%else%>
                      <li><a href="/users/sign_up">Sign Up</a></li>
                      <li><a href="/users/sign_in">Sign In</a></li>
                    <%end%>
                </ul>
            </div>
        </div>
    </header>  


  

<%= yield %>

  <footer>
        <p>copyright Acme &copy; 2019</p>
    </footer>
    
</body>
</html>

app/views/likes/toggle.html.erb
<h1>Likes#toggle</h1>
<p>Find me in app/views/likes/toggle.html.erb</p>